DROP TABLE ODONTOLOGOS  IF EXISTS;
CREATE TABLE ODONTOLOGOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
MATRICULA INT NOT NULL,
NOMBRE VARCHAR(25) NOT NULL,
APELLIDO VARCHAR(25) NOT NULL

);

INSERT INTO ODONTOLOGOS VALUES (DEFAULT, 123, 'JUAN', 'PEREZ'),(DEFAULT,456, 'PEDRO', 'RODRIGUEZ');